### ISSUE TITLE
Среда разработки QDK

### ISSUE THREAD

**Issue by alegenyas** [MicrosoftDocs/quantum-docs-pr.ru-RU#1]
QDK доступен для нескольких сред разработки. Выберите предпочитаемую настройку из следующих разделов:
Установка Q# для C#:
Установка Q# для Python
Установка Q# для Jupyter Notebook

 Здравствуйте Скажите пожалуйста Могу ли я установить все три среды, одновременно, для более эффективного взаимодействия и реализации разных проектов на 1 платформе (фундаменте). В самом деле, это было бы очень удобно, для нас

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: 6aa31568-61b3-cb7f-bda5-d88134449907
* Version Independent ID: b44cf531-1535-cc4c-873f-d33b7f887e11
* Content: [Сведения об установке пакета средств разработки Microsoft Quantum (QDK) - Microsoft Quantum](https://docs.microsoft.com/ru-ru/quantum/install-guide/#feedback)
* Content Source: [articles/install-guide/index.md](https://github.com/MicrosoftDocs/quantum-docs-pr.ru-RU/blob/live-sxs/articles/install-guide/index.md)
* Product: **quantum**
* GitHub Login: @natke
* Microsoft Alias: **nakersha**

**Comment by srvbpigh** [comment]
Hello, @alegenyas
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
Здравствуйте, @alegenyas!  

Благодарим Вас за участие. Ваш отзыв связан с исходной документацией.  

Поэтому мы переносим Вашу заявку в репозиторий по английскому языку. Ее состояние можно просмотреть здесь: https://github.com/MicrosoftDocs/quantum-docs-pr/issues/753.  

Мы очень ценим Ваш вклад в наши статьи.   

С наилучшими пожеланиями,  
Международная команда поддержки документации Майкрософт
